services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=api'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=dba'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'